### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'image_encoder'

### ISSUE THREAD

**Issue by Mojitoooooo** [zhoudaquan/ChatAnything#7]
Traceback (most recent call last):
  File "/home/miniconda3/envs/chatanything/lib/python3.8/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/miniconda3/envs/chatanything/lib/python3.8/site-packages/gradio/blocks.py", line 1435, in process_api
    result = await self.call_function(
  File "/home/miniconda3/envs/chatanything/lib/python3.8/site-packages/gradio/blocks.py", line 1107, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/miniconda3/envs/chatanything/lib/python3.8/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/miniconda3/envs/chatanything/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/miniconda3/envs/chatanything/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/miniconda3/envs/chatanything/lib/python3.8/site-packages/gradio/utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "/home/ChatAnything/utils.py", line 157, in generate_init_face_video
    anything_facemaker = load_face_generator(
  File "/home/ChatAnything/utils.py", line 259, in load_face_generator
    anything_facemaker.load_model(safety_checker=None)
  File "/home/ChatAnything/chat_anything/face_generator/long_prompt_control_generator.py", line 39, in load_model
    super().load_model(*args, **kwargs)
  File "/home/ChatAnything/chat_anything/face_generator/long_prompt_generator.py", line 44, in load_model
    pipe_longprompt = StableDiffusionLongPromptWeightingPipeline(**pipe.components)
TypeError: __init__() got an unexpected keyword argument 'image_encoder'

**Comment by 2454511550Lin** [comment]
Any follow-up on this? I got the same error when I tried to generate a character.
